export { default as defaultIcon } from './icons/info-circle-icon-orange.svg'
export { default as hoveredIcon } from './icons/info-circle-icon-hover-orange.svg'
export { default as RGSlogo } from './contents/RGS-en-logo.svg'
export { default as HClogo } from './contents/HC-logo-en.svg'
export { default as quoteIcon } from './icons/Quote-Decoration-Icon.svg'
export { default as quoteIconOrange } from './icons/Quote-Decoration-Icon-Orange.svg'
export { default as newBlackPlaneUrl } from './blue_plane.glb?url'
export { default as citrusOrchardExrUrl } from './bgs/kloofendal_48d_partly_cloudy_puresky_2k.exr?url'

export { default as RadioReceiver } from './images/1-Radio-receiver.png'
export { default as Nameplates } from './images/2-Nameplates.jpg'
export { default as Cylinder } from './images/3-Cylinder.jpg'
