export { default as defaultIcon } from './icons/info-circle-icon-orange.svg'
export { default as hoveredIcon } from './icons/info-circle-icon-hover-orange.svg'
export { default as RGSlogo } from './contents/RGS-en-logo.svg'
export { default as HClogo } from './contents/HC-logo-en.svg'
export { default as quoteIcon } from './icons/Quote-Decoration-Icon.svg'
export { default as quoteIconOrange } from './icons/Quote-Decoration-Icon-Orange.svg'
export { default as newBlackPlaneUrl } from './blue_plane.glb?url'
export { default as citrusOrchardExrUrl } from './bgs/citrus_orchard_puresky_2k.exr?url'

export { default as RadioReceiver } from './images/1-Radio-receiver.jpg'
export { default as propeller } from './images/2-Propeller.jpg'
export { default as tail } from './images/3-Tail.jpg'
